# Starcraft path (where StarCraft.exe is located) - if unset, looks for an installed Starcraft
starcraft_path = 'C:\Users\WDAGUtilityAccount\Desktop\shotgun'

# Java executable to use for java bots
# java_path = '...\java.exe'